### ISSUE TITLE
Misleading return type

### ISSUE THREAD

**Issue by parva-jain** [filecoin-project/filecoin-solidity#26]
The MarketAPI.getDealTerm() function returns the start epoch and duration(in epoch) of a deal, but the its return type i.e. MarketTypes.GetDealTermReturn is having start epoch and end epoch as variable. The duration can be misinterpreted as end epoch for deal. 

Example - 
[Here](https://github.com/filecoin-project/raas-starter-kit/blob/49f344c94be8d81c83163f46403c1396558d0c9c/contracts/DealStatus.sol#L92), in getExpiringDeals function's if statement, return value from MarketAPI.getDealTerm is considered as end epoch and hence the statement is wrong and giving wrong output everytime.

**Comment by dzmbs** [comment]
Hi @parva-jain, thanks for the heads up. Unfortunately, we can't change the zondax package because we don't maintain it, but I've opened a draft [PR](https://github.com/filecoin-project/filecoin-solidity/pull/30) to address this and include it in the new package that Filecoin will publish. For now, for uint64 `endEpoch` value, you can use something like this:
```solidity
function getEndEpochValue(uint64 dealId) internal returns (uint64 endEpoch) {
        MarketTypes.GetDealTermReturn memory dealTerm = MarketAPI.getDealTerm(
            dealId
        );
        endEpoch = uint64(
            CommonTypes.ChainEpoch.unwrap(dealTerm.start) +
                CommonTypes.ChainEpoch.unwrap(dealTerm.end)
        );
    }
```

**Comment by parva-jain** [comment]
Alright!!
